install:
    # Define the version of micromamba to download
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        MICROMAMBA_OS=$MICROMAMBA_OSX;
        wget -qO- https://micromamba.snakepit.net/api/micromamba/osx-64/latest | tar -xvj bin/micromamba;
      fi
    ./micromamba shell init -s bash -p ~/micromamba
    micromamba activate
    micromamba install mamba -c conda-forge

language: r
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

r_packages:
  - Rcpp

script:
  - set +e
  - R CMD build .
  - R CMD check rhumba_0.0.0.9000.tar.gz --as-cran --no-manual
  - cat /home/travis/build/marimeireles/caramba/rhumba.Rcheck/00install.out