language: r
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

r_packages:
  - Rcpp

script:
  - autoconf
  - R CMD build .
  - R CMD check rhumba_0.0.0.9000.tar.gz --as-cran --no-manual