language: r
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

r_packages:
  - Rcpp

script:
  - set +e
  - R CMD build .
  - R CMD check rhumba_0.0.0.9000.tar.gz --as-cran --no-manual
  - cat /home/travis/build/marimeireles/caramba/rhumba.Rcheck/00install.out